plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')

    shadowBundle(implementation("com.electronwill.night-config:core:$rootProject.nightconfig_version")) { transitive = false }
    shadowBundle(implementation("com.electronwill.night-config:toml:$rootProject.nightconfig_version")) { transitive = false }
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'minecraft_version', rootProject.minecraft_version
    inputs.property 'fabric_loader_version', rootProject.fabric_loader_version
    inputs.property 'mod_id', rootProject.mod_id
    inputs.property 'mod_name', rootProject.mod_name
    inputs.property 'mod_authors', rootProject.mod_authors
    inputs.property 'mod_license', rootProject.mod_license
    inputs.property 'mod_description', rootProject.mod_description

    filesMatching('fabric.mod.json') {
        expand(
                version: project.version,
                minecraft_version: rootProject.minecraft_version,
                fabric_loader_version: rootProject.fabric_loader_version,
                mod_id: rootProject.mod_id,
                mod_name: rootProject.mod_name,
                mod_authors: rootProject.mod_authors,
                mod_license: rootProject.mod_license,
                mod_description: rootProject.mod_description
        )
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
    mergeServiceFiles()

    relocate("com.electronwill", "com.saunhardy.afkstatus.shadow.com.electronwill")
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
