org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.1.1
mod_id = afkstatus
mod_name = AFKStatus
mod_authors = saunhardy
mod_license = All Rights Reserved
mod_description = AFKStatus\nSimple AFK mod.
maven_group = com.saunhardy.afkstatus
archives_name = afkstatus
enabled_platforms = fabric,forge,neoforge

# Minecraft properties
minecraft_version = 1.21.1
minecraft_version_range = [1.21.1,1.22)

# Forge
forge_version = 1.21.1-52.1.4
forge_version_range = [52,)
loader_version_range = [52,)

# NeoForge
neoforge_version = 21.1.197
neoforge_loader_version_range = [4,)
neoforge_version_range = [21.1,)

# Fabric
fabric_loader_version = 0.16.14
fabric_api_version = 0.115.0+1.21.1

# Shared libs
nightconfig_version = 3.6.7
