org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.2.0
mod_id = afkstatus
mod_name = AFKStatus
mod_authors = saunhardy
mod_license = All Rights Reserved
mod_description = AFKStatus\nSimple AFK mod.
maven_group = com.saunhardy.afkstatus
archives_name = afkstatus
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.4
minecraft_version_range = [1.21.4,1.21.5)

# NeoForge
neoforge_version = 21.4.157
neoforge_loader_version_range = [4,)
neoforge_version_range = [21.4,)

# Fabric
fabric_loader_version = 0.16.14
fabric_api_version = 0.119.4+1.21.4

# Shared libs
nightconfig_version = 3.6.7
