architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    // Provided at runtime by Forge; bundled into the Fabric jar via shadow.
    compileOnly "com.electronwill.night-config:core:$rootProject.nightconfig_version"
    compileOnly "com.electronwill.night-config:toml:$rootProject.nightconfig_version"
}
