plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:$rootProject.neoforge_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionNeoForge')

    shadowBundle(implementation("com.electronwill.night-config:core:$rootProject.nightconfig_version")) { transitive = false }
    shadowBundle(implementation("com.electronwill.night-config:toml:$rootProject.nightconfig_version")) { transitive = false }
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'minecraft_version_range', rootProject.minecraft_version_range
    inputs.property 'neoforge_version', rootProject.neoforge_version
    inputs.property 'neoforge_version_range', rootProject.neoforge_version_range
    inputs.property 'neoforge_loader_version_range', rootProject.neoforge_loader_version_range
    inputs.property 'mod_id', rootProject.mod_id
    inputs.property 'mod_name', rootProject.mod_name
    inputs.property 'mod_authors', rootProject.mod_authors
    inputs.property 'mod_license', rootProject.mod_license
    inputs.property 'mod_description', rootProject.mod_description

    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand(
                version: project.version,
                minecraft_version: rootProject.minecraft_version,
                minecraft_version_range: rootProject.minecraft_version_range,
                neoforge_version: rootProject.neoforge_version,
                neoforge_version_range: rootProject.neoforge_version_range,
                neoforge_loader_version_range: rootProject.neoforge_loader_version_range,
                mod_id: rootProject.mod_id,
                mod_name: rootProject.mod_name,
                mod_authors: rootProject.mod_authors,
                mod_license: rootProject.mod_license,
                mod_description: rootProject.mod_description
        )
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
    mergeServiceFiles()

    relocate("com.electronwill", "com.saunhardy.afkstatus.shadow.com.electronwill")
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
