name: Sync afkstatus Java files to other branches

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-afkstatus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: neoforge-1.21.1

      - name: Save afkstatus files
        run: |
          mkdir -p temp-afkstatus
          cp -r src/main/java/com/saunhardy/afkstatus temp-afkstatus/

      - name: Sync to target branches
        run: |
          for BRANCH in neoforge-1.21.{2..8}; do
            echo "Syncing to $BRANCH"

            git switch $BRANCH

            rm -rf src/main/java/com/saunhardy/afkstatus
            mkdir -p src/main/java/com/saunhardy
            cp -r temp-afkstatus/afkstatus src/main/java/com/saunhardy/

            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add src/main/java/com/saunhardy/afkstatus
            git commit -m "Sync afkstatus files from neoforge-1.21.1" || echo "No changes to commit"
            git push origin $BRANCH
          done
